import type { BlockStyleDefaults } from './site-theme-tokens';

/**
 * The default CSS expression for each stylable property (docs/adr/0022) of
 * every block type — copied 1:1 from the fallback the block's `.astro`
 * already uses (`var(--kometio-override-radius, var(--radius))`), not
 * invented: this is the exact same source of truth, only declared here
 * rather than remaining visible solely inside a CSS file. It lives in
 * shared-types (not in block-registry) because BOTH `libs/block-registry`
 * (BlockDescriptor.defaultStyle, for editor-app's picker) AND
 * `apps/public-site` (resolve-theme-block-style-defaults.ts, for the
 * `/api/themes/current/block-style-defaults` endpoint) need it — the same
 * reason as `block-style-overrides.ts` in this same file, and not merely a
 * layering whim: making apps/public-site depend on `@kometio/block-registry`
 * (a package oriented around the editor's React components, not pure data)
 * caused a real TypeScript resolution conflict between Astro's
 * configuration and the registry's React test files — see this file's
 * history for the detail. shared-types does not have that problem, being
 * already a pure dependency of both apps. A reference to a theme custom
 * property (`var(--x)`) is resolved against the active theme's `theme.css`
 * on the public-site side only; a literal (`'transparent'`, `'0.5rem'`)
 * passes through unchanged.
 */
export const BLOCK_STYLE_DEFAULTS: Record<string, BlockStyleDefaults> = {
  Anchor: {
    maxWidth: 'none',
  },
  ReadingProgress: {
    backgroundColor: 'var(--primary)',
    minHeight: '3px',
  },
  TableOfContents: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.375rem',
  },
  SubPages: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.75rem',
  },
  SiblingPages: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  SiteMap: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.25rem',
  },
  List: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.5rem',
  },
  ListItem: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  MediaText: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '2rem',
  },
  Faq: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  Marquee: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '2.5rem',
  },
  ContactDetails: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.5rem',
  },
  OpeningHours: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  FileDownload: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: 'var(--radius)',
    paddingX: '1rem',
    paddingY: '0.75rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
  },
  // The shop window (the last family of the hundred-blocks plan).
  ProductGrid: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '1.5rem',
  },
  ProductCard: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: 'var(--radius)',
    paddingX: '1rem',
    paddingY: '1rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
  },
  ProductGallery: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: 'var(--radius)',
    paddingX: '0',
    paddingY: '0',
    gap: '0.75rem',
    maxWidth: '40rem',
  },
  DiscountPrice: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  // A Button, drawn by Button.astro — the same defaults, or the two would disagree about the same element.
  BuyButton: {
    backgroundColor: 'var(--primary)',
    textColor: 'var(--primary-foreground)',
    borderRadius: 'var(--radius)',
    paddingX: '1.25rem',
    paddingY: '0.5rem',
    gap: '0.5em',
  },
  ProductVariants: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.5rem',
  },
  ProductReviews: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '1.5rem',
  },
  // A Testimonial, drawn by Testimonial.astro.
  ProductReview: {
    backgroundColor: 'transparent',
    textColor: 'var(--foreground)',
    borderRadius: '12px',
    paddingX: '1.5rem',
    paddingY: '1.5rem',
  },
  ComparisonTable: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: 'var(--radius)',
    paddingX: '0',
    paddingY: '0',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
  },
  ComparisonRow: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    paddingX: '1rem',
    paddingY: '0.75rem',
  },
  PromoCode: {
    backgroundColor: 'var(--muted)',
    textColor: 'inherit',
    borderRadius: 'var(--radius)',
    paddingX: '1rem',
    paddingY: '0.75rem',
    borderWidth: '1px',
    borderStyle: 'dashed',
    borderColor: 'var(--border)',
  },
  ShippingReturns: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '1.5rem',
  },
  TrustBadges: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.75rem',
  },
  // A local business.
  RestaurantMenu: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '1.25rem',
  },
  MenuItem: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  EventList: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '1.5rem',
  },
  EventItem: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: 'var(--radius)',
    paddingX: '1rem',
    paddingY: '1rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
  },
  StickyContactBar: {
    backgroundColor: 'var(--background)',
    textColor: 'var(--foreground)',
    paddingX: '0.5rem',
    paddingY: '0.5rem',
  },
  ShareButtons: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.5rem',
  },
  CookiePreferences: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  // Editorial content.
  Steps: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '1.5rem',
  },
  Step: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  SpecList: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '2rem',
  },
  SpecItem: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    paddingX: '0',
    paddingY: '0.5rem',
  },
  // The bar is the block: its colour is the fill, its radius the track's, its min height the thickness.
  ProgressBar: {
    backgroundColor: 'var(--primary)',
    textColor: 'inherit',
    borderRadius: '999px',
    minHeight: '0.5rem',
  },
  // A TeamMember, drawn by TeamMember.astro.
  ProfileCard: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  // The same consent gate as VideoEmbed and MapEmbed, so the same real fallbacks.
  BookingEmbed: {
    borderRadius: '8px',
    borderWidth: '0',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
    boxShadow: 'none',
    maxWidth: 'none',
  },
  FileList: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.5rem',
  },
  Glossary: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '1rem',
  },
  GlossaryTerm: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  // A Quote, drawn by Quote.astro, with the room a pull quote stands in.
  PullQuote: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    paddingX: '0',
    paddingY: '1.5rem',
  },
  ImageHotspots: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: 'var(--radius)',
    paddingX: '0',
    paddingY: '0',
  },
  Hotspot: {
    backgroundColor: 'var(--primary)',
    textColor: 'var(--primary-foreground)',
  },
  // A Gallery, drawn by Gallery.astro.
  MasonryGallery: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.5rem',
  },
  VideoPlaylist: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '1rem',
  },
  AuthorBox: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: 'var(--radius)',
    paddingX: '1.25rem',
    paddingY: '1.25rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
  },
  AccordionItem: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0.75rem',
  },
  Accordion: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  Audio: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  BackToTop: {
    backgroundColor: 'var(--primary)',
    textColor: 'var(--primary-foreground)',
    borderRadius: '50%',
    boxShadow: '0 4px 12px rgb(0 0 0 / 20%)',
  },
  Banner: {
    backgroundColor: 'var(--secondary)',
    textColor: 'inherit',
    borderRadius: '12px',
    paddingX: '1.5rem',
    paddingY: '2.5rem',
    // What the block's own CSS falls back to: no frame by default, and
    // the gap the `split` variant opens between the words and the button.
    borderWidth: '0',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
    gap: '1.5rem',
  },
  BeforeAfter: {
    borderRadius: '8px',
    borderWidth: '0',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
    boxShadow: 'none',
    maxWidth: 'none',
  },
  Breadcrumb: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.4rem',
  },
  Button: {
    backgroundColor: 'var(--primary)',
    textColor: 'var(--primary-foreground)',
    borderRadius: 'var(--radius)',
    paddingX: '1.25rem',
    paddingY: '0.5rem',
    // The space between an icon and its label (ADR-0056).
    gap: '0.5em',
  },
  Callout: {
    // The tone's own colours are deliberately literal and stay put (see
    // Callout.astro) — what is stylable here is the box around them.
    borderRadius: 'var(--radius)',
    paddingX: '1.25rem',
    paddingY: '1rem',
  },
  Code: {
    backgroundColor: 'transparent',
    borderRadius: 'var(--radius)',
    paddingX: '1.25rem',
    paddingY: '1rem',
  },
  Column: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '1rem',
  },
  Columns: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    // The space between columns, which used to be a hardcoded 1.5rem
    // (ADR-0050) — this is that same value, so a row nobody has touched
    // looks exactly as it did.
    gap: '1.5rem',
  },
  Card: {
    // `--background` and not a `--card` token: this theme vocabulary has
    // no such token, and inventing one here would name a custom property
    // no theme.css defines — the reference would resolve to nothing and
    // the card would come out transparent (ADR-0022 resolves these
    // against the active theme, it does not create them).
    backgroundColor: 'var(--background)',
    textColor: 'inherit',
    borderRadius: 'var(--radius)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
    boxShadow: 'none',
    paddingX: '1.25rem',
    paddingY: '1.25rem',
    gap: '0.75rem',
    contentAlign: 'stretch',
    maxWidth: 'none',
    minHeight: 'auto',
  },
  Container: {
    // The preset's own value at the block's default (`padding: 'md'`) and
    // `background: 'none'` — the editor opens showing what a Container
    // actually looks like now, and the preset stays the fallback these
    // free values sit in front of (ADR-0050).
    backgroundColor: 'transparent',
    paddingX: '2rem',
    paddingY: '2rem',
    flexDirection: 'column',
    textColor: 'inherit',
    borderRadius: '0.5rem',
    // Each one is the fallback the block's own CSS already declares, so
    // the editor opens showing what the container looks like right now
    // rather than an empty box (ADR-0022's follow-up).
    borderWidth: '0',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
    boxShadow: 'none',
    backgroundImage: 'none',
    backgroundPosition: 'center',
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    overlayColor: 'transparent',
    minHeight: 'auto',
    maxWidth: 'none',
    gap: '1rem',
    contentAlign: 'stretch',
    contentJustify: 'flex-start',
  },
  Countdown: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  Divider: {
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
    maxWidth: 'none',
  },
  EmbedHtml: {
    backgroundColor: 'transparent',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  FeatureGrid: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  Feature: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    // What `.kometio-feature--inline` falls back to.
    gap: '1rem',
  },
  Form: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  Gallery: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.5rem',
  },
  HamburgerMenu: {
    backgroundColor: 'var(--background)',
    textColor: 'inherit',
    borderRadius: '8px',
    paddingX: '1rem',
    paddingY: '1rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
    boxShadow: '0 8px 24px rgb(0 0 0 / 12%)',
  },
  Hero: {
    backgroundColor: 'transparent',
    textColor: 'var(--foreground)',
    borderRadius: '0',
    boxShadow: 'none',
    backgroundImage: 'none',
    backgroundPosition: 'center',
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    overlayColor: 'transparent',
    minHeight: 'auto',
    // The values the block already rendered — `sm:py-28`'s 7rem is the
    // wide-screen half of a responsive default, so the resolved default
    // shown in the editor is the base one.
    contentAlign: 'stretch',
    gap: '0',
    paddingX: '0',
    paddingY: '5rem',
    maxWidth: '48rem',
  },
  Heading: {
    textColor: 'inherit',
  },
  Icon: {
    textColor: 'currentColor',
  },
  Image: {
    borderRadius: '0',
    borderWidth: '0',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
    boxShadow: 'none',
    maxWidth: 'none',
  },
  ImageSlider: {
    borderRadius: '0',
    boxShadow: 'none',
    maxWidth: 'none',
  },
  LanguageSwitcher: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.5rem',
  },
  Link: {
    backgroundColor: 'transparent',
    textColor: 'var(--primary)',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  LogoStrip: {
    backgroundColor: 'transparent',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  MapEmbed: {
    // ConsentGatedEmbed's own fallback: this said 0 while every embed drew 8px.
    borderRadius: '8px',
    borderWidth: '0',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
    boxShadow: 'none',
    maxWidth: 'none',
  },
  Nav: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '1rem',
  },
  NavDropdown: {
    backgroundColor: 'var(--background)',
    textColor: 'inherit',
    borderRadius: '8px',
    paddingX: '0.75rem',
    paddingY: '0.75rem',
    gap: '0.25rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
    boxShadow: '0 8px 24px rgb(0 0 0 / 12%)',
  },
  NavLink: {
    backgroundColor: 'transparent',
    textColor: 'var(--primary)',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.4em',
  },
  NewsletterSignup: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    maxWidth: '24rem',
  },
  PricingPlan: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '12px',
    paddingX: '1.5rem',
    paddingY: '1.5rem',
  },
  PricingTable: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  PromoBar: {
    backgroundColor: 'var(--primary)',
    textColor: 'var(--primary-foreground)',
    borderRadius: '0',
    paddingX: '2.5rem',
    paddingY: '0.75rem',
  },
  Quote: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  Rating: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  Section: {
    // The only thing the wrapper owns — see section.block.ts on why it
    // owns nothing else.
    maxWidth: 'none',
  },
  ArticleMeta: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  ArticleNav: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  RelatedPages: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.75rem',
  },
  TermList: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.5rem',
  },
  PageGrid: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.75rem',
  },
  SearchBox: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.5rem',
  },
  Carousel: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '1.5rem',
  },
  SocialLink: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '50%',
    paddingX: '0',
    paddingY: '0',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
  },
  SocialLinks: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
    gap: '0.75rem',
  },
  Spacer: {
    minHeight: '2rem',
    backgroundColor: 'transparent',
  },
  Stat: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  StatsCounter: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  Tab: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '1rem',
  },
  Table: {
    // These land on the cells rather than the scroll wrapper: padding and
    // borders are what "styling a table" means (see Table.astro).
    backgroundColor: 'var(--muted)',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0.75rem',
    paddingY: '0.5rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
  },
  Tabs: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  TeamMember: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  Team: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  Testimonial: {
    backgroundColor: 'transparent',
    textColor: 'var(--foreground)',
    borderRadius: '12px',
    paddingX: '1.5rem',
    paddingY: '1.5rem',
  },
  Testimonials: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '0',
    paddingY: '0',
  },
  Text: {
    textColor: 'inherit',
  },
  Timeline: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
  },
  TimelineStep: {
    backgroundColor: 'transparent',
    textColor: 'inherit',
    borderRadius: '0',
    paddingX: '1rem',
    paddingY: '1.5rem',
  },
  VideoEmbed: {
    // ConsentGatedEmbed's own fallback: this said 0 while every embed drew 8px.
    borderRadius: '8px',
    borderWidth: '0',
    borderStyle: 'solid',
    borderColor: 'var(--border)',
    boxShadow: 'none',
    maxWidth: 'none',
  },
  VideoFile: {
    borderRadius: '0',
    boxShadow: 'none',
    maxWidth: '100%',
    backgroundColor: '#000',
  },
  WhatsAppButton: {
    backgroundColor: '#25d366',
    borderRadius: '50%',
    boxShadow: '0 4px 12px rgb(0 0 0 / 20%)',
  },
};
