import type { z } from 'zod';
import { authorBoxPropsSchema } from './author';
import {
  bookingEmbedPropsSchema,
  buyButtonPropsSchema,
  comparisonRowPropsSchema,
  comparisonTablePropsSchema,
  cookiePreferencesPropsSchema,
  discountPricePropsSchema,
  eventItemPropsSchema,
  eventListPropsSchema,
  fileListPropsSchema,
  glossaryPropsSchema,
  glossaryTermPropsSchema,
  hotspotPropsSchema,
  imageHotspotsPropsSchema,
  masonryGalleryPropsSchema,
  menuItemPropsSchema,
  productCardPropsSchema,
  productGalleryPropsSchema,
  productGridPropsSchema,
  productReviewPropsSchema,
  productReviewsPropsSchema,
  productVariantsPropsSchema,
  profileCardPropsSchema,
  progressBarPropsSchema,
  promoCodePropsSchema,
  pullQuotePropsSchema,
  restaurantMenuPropsSchema,
  shareButtonsPropsSchema,
  shippingReturnsPropsSchema,
  specItemPropsSchema,
  specListPropsSchema,
  stepPropsSchema,
  stepsPropsSchema,
  stickyContactBarPropsSchema,
  trustBadgesPropsSchema,
  videoPlaylistPropsSchema,
} from './commerce-local-content-blocks';
import {
  anchorPropsSchema,
  contactDetailsPropsSchema,
  faqPropsSchema,
  fileDownloadPropsSchema,
  listItemPropsSchema,
  listPropsSchema,
  marqueePropsSchema,
  mediaTextPropsSchema,
  openingHoursPropsSchema,
  readingProgressPropsSchema,
  siblingPagesPropsSchema,
  siteMapPropsSchema,
  subPagesPropsSchema,
  tableOfContentsPropsSchema,
} from './content-and-navigation-blocks';
import {
  accordionItemPropsSchema,
  accordionPropsSchema,
  articleMetaPropsSchema,
  articleNavPropsSchema,
  audioPropsSchema,
  backToTopPropsSchema,
  bannerPropsSchema,
  beforeAfterPropsSchema,
  breadcrumbPropsSchema,
  buttonPropsSchema,
  calloutPropsSchema,
  cardPropsSchema,
  carouselPropsSchema,
  codePropsSchema,
  columnPropsSchema,
  columnsPropsSchema,
  containerPropsSchema,
  countdownPropsSchema,
  dividerPropsSchema,
  embedHtmlPropsSchema,
  featureGridPropsSchema,
  featurePropsSchema,
  formBlockPropsSchema,
  galleryPropsSchema,
  hamburgerMenuPropsSchema,
  headingPropsSchema,
  heroPropsSchema,
  iconPropsSchema,
  imagePropsSchema,
  imageSliderPropsSchema,
  languageSwitcherPropsSchema,
  linkPropsSchema,
  logoStripPropsSchema,
  mapEmbedPropsSchema,
  navDropdownPropsSchema,
  navLinkPropsSchema,
  navPropsSchema,
  newsletterSignupPropsSchema,
  pageGridPropsSchema,
  pricingPlanPropsSchema,
  pricingTablePropsSchema,
  promoBarPropsSchema,
  quotePropsSchema,
  ratingPropsSchema,
  relatedPagesPropsSchema,
  searchBoxPropsSchema,
  socialLinkPropsSchema,
  socialLinksPropsSchema,
  spacerPropsSchema,
  statPropsSchema,
  statsCounterPropsSchema,
  tabPropsSchema,
  tablePropsSchema,
  tabsPropsSchema,
  teamMemberPropsSchema,
  teamPropsSchema,
  termListPropsSchema,
  testimonialPropsSchema,
  testimonialsPropsSchema,
  textPropsSchema,
  timelinePropsSchema,
  timelineStepPropsSchema,
  videoEmbedPropsSchema,
  videoFilePropsSchema,
  whatsAppButtonPropsSchema,
} from './content-model';
import { sectionPropsSchema } from './reusable-section';

/**
 * Every block type Kometio knows, and the schema its props are checked
 * against — the one list both the public site and the API read.
 *
 * It lived only inside the public site's BlockRenderer, next to the Astro
 * component each type renders with, where nothing else could reach it: the
 * API had no way to know which block types exist or what a valid block
 * looks like. Generating a page from a prompt needs exactly that, and so
 * will any block from outside the core. The renderer now reads its schema
 * from here, so the two cannot drift apart.
 *
 * A theme's own block types are not listed: their schemas travel with the
 * theme (docs/adr/0021).
 */
export const BLOCK_PROPS_SCHEMAS = {
  Hero: heroPropsSchema,
  Section: sectionPropsSchema,
  Card: cardPropsSchema,
  Heading: headingPropsSchema,
  Text: textPropsSchema,
  Image: imagePropsSchema,
  Gallery: galleryPropsSchema,
  Form: formBlockPropsSchema,
  Quote: quotePropsSchema,
  Callout: calloutPropsSchema,
  Rating: ratingPropsSchema,
  Countdown: countdownPropsSchema,
  EmbedHtml: embedHtmlPropsSchema,
  Code: codePropsSchema,
  Table: tablePropsSchema,
  NavLink: navLinkPropsSchema,
  LanguageSwitcher: languageSwitcherPropsSchema,
  ArticleMeta: articleMetaPropsSchema,
  AuthorBox: authorBoxPropsSchema,
  ArticleNav: articleNavPropsSchema,
  RelatedPages: relatedPagesPropsSchema,
  Anchor: anchorPropsSchema,
  ReadingProgress: readingProgressPropsSchema,
  TableOfContents: tableOfContentsPropsSchema,
  SubPages: subPagesPropsSchema,
  SiblingPages: siblingPagesPropsSchema,
  SiteMap: siteMapPropsSchema,
  List: listPropsSchema,
  ListItem: listItemPropsSchema,
  MediaText: mediaTextPropsSchema,
  Faq: faqPropsSchema,
  Marquee: marqueePropsSchema,
  ContactDetails: contactDetailsPropsSchema,
  OpeningHours: openingHoursPropsSchema,
  FileDownload: fileDownloadPropsSchema,
  ProductGrid: productGridPropsSchema,
  ProductCard: productCardPropsSchema,
  ProductGallery: productGalleryPropsSchema,
  DiscountPrice: discountPricePropsSchema,
  BuyButton: buyButtonPropsSchema,
  ProductVariants: productVariantsPropsSchema,
  ProductReviews: productReviewsPropsSchema,
  ProductReview: productReviewPropsSchema,
  ComparisonTable: comparisonTablePropsSchema,
  ComparisonRow: comparisonRowPropsSchema,
  PromoCode: promoCodePropsSchema,
  ShippingReturns: shippingReturnsPropsSchema,
  TrustBadges: trustBadgesPropsSchema,
  RestaurantMenu: restaurantMenuPropsSchema,
  MenuItem: menuItemPropsSchema,
  EventList: eventListPropsSchema,
  EventItem: eventItemPropsSchema,
  StickyContactBar: stickyContactBarPropsSchema,
  ShareButtons: shareButtonsPropsSchema,
  CookiePreferences: cookiePreferencesPropsSchema,
  Steps: stepsPropsSchema,
  Step: stepPropsSchema,
  SpecList: specListPropsSchema,
  SpecItem: specItemPropsSchema,
  ProgressBar: progressBarPropsSchema,
  ProfileCard: profileCardPropsSchema,
  BookingEmbed: bookingEmbedPropsSchema,
  FileList: fileListPropsSchema,
  Glossary: glossaryPropsSchema,
  GlossaryTerm: glossaryTermPropsSchema,
  PullQuote: pullQuotePropsSchema,
  ImageHotspots: imageHotspotsPropsSchema,
  Hotspot: hotspotPropsSchema,
  MasonryGallery: masonryGalleryPropsSchema,
  VideoPlaylist: videoPlaylistPropsSchema,
  TermList: termListPropsSchema,
  PageGrid: pageGridPropsSchema,
  Breadcrumb: breadcrumbPropsSchema,
  SearchBox: searchBoxPropsSchema,
  Nav: navPropsSchema,
  HamburgerMenu: hamburgerMenuPropsSchema,
  NavDropdown: navDropdownPropsSchema,
  Divider: dividerPropsSchema,
  VideoFile: videoFilePropsSchema,
  Audio: audioPropsSchema,
  Spacer: spacerPropsSchema,
  Icon: iconPropsSchema,
  SocialLinks: socialLinksPropsSchema,
  SocialLink: socialLinkPropsSchema,
  Carousel: carouselPropsSchema,
  Columns: columnsPropsSchema,
  Container: containerPropsSchema,
  PromoBar: promoBarPropsSchema,
  BackToTop: backToTopPropsSchema,
  WhatsAppButton: whatsAppButtonPropsSchema,
  Accordion: accordionPropsSchema,
  AccordionItem: accordionItemPropsSchema,
  Tabs: tabsPropsSchema,
  Tab: tabPropsSchema,
  Banner: bannerPropsSchema,
  Button: buttonPropsSchema,
  Link: linkPropsSchema,
  FeatureGrid: featureGridPropsSchema,
  Feature: featurePropsSchema,
  VideoEmbed: videoEmbedPropsSchema,
  MapEmbed: mapEmbedPropsSchema,
  ImageSlider: imageSliderPropsSchema,
  BeforeAfter: beforeAfterPropsSchema,
  LogoStrip: logoStripPropsSchema,
  Testimonials: testimonialsPropsSchema,
  Testimonial: testimonialPropsSchema,
  Team: teamPropsSchema,
  TeamMember: teamMemberPropsSchema,
  PricingTable: pricingTablePropsSchema,
  PricingPlan: pricingPlanPropsSchema,
  StatsCounter: statsCounterPropsSchema,
  Stat: statPropsSchema,
  Timeline: timelinePropsSchema,
  TimelineStep: timelineStepPropsSchema,
  NewsletterSignup: newsletterSignupPropsSchema,
  Column: columnPropsSchema,
} as const satisfies Record<string, z.ZodType>;

export type BlockType = keyof typeof BLOCK_PROPS_SCHEMAS;

export function isBlockType(type: string): type is BlockType {
  return Object.hasOwn(BLOCK_PROPS_SCHEMAS, type);
}

/** Every core block type, in the order the renderer declares them. */
export const BLOCK_TYPES: readonly BlockType[] =
  Object.keys(BLOCK_PROPS_SCHEMAS).filter(isBlockType);
