import { createElement } from 'react';
import {
  Square as BlockIconFallback,
  AlignJustify,
  ArrowUp,
  ArrowLeftRight,
  CalendarDays,
  Layers,
  AtSign,
  BadgeCheck,
  Building2,
  ChartColumn,
  ChevronDown,
  ChevronDownSquare,
  ChevronRight,
  ChevronsUpDown,
  CircleDot,
  ClipboardList,
  Code,
  CodeXml,
  Columns3,
  File,
  Folder,
  GalleryHorizontal,
  GalleryHorizontalEnd,
  Grid3x3,
  Hash,
  Heading,
  Image,
  Images,
  Languages,
  LayoutGrid,
  LayoutPanelTop,
  Link,
  Link2,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquareQuote,
  MessageSquareWarning,
  Milestone,
  Minus,
  MonitorPlay,
  MousePointerClick,
  MoveVertical,
  Music,
  PanelTop,
  Quote,
  Receipt,
  RectangleVertical,
  Rows3,
  Search,
  Share2,
  SlidersHorizontal,
  Smile,
  Square,
  SquareStack,
  Star,
  Table,
  Tag,
  Tags,
  Timer,
  Type,
  User,
  UserPen,
  Users,
  Video,
  type LucideIcon,
  Anchor,
  BookOpenCheck,
  ListTree,
  FolderTree,
  MoveHorizontal,
  Network,
  List,
  Dot,
  LayoutPanelLeft,
  CircleHelp,
  Infinity as InfinityIcon,
  Contact,
  Clock,
  FileDown,
  Store,
  ShoppingBag,
  GalleryThumbnails,
  BadgePercent,
  ShoppingCart,
  SwatchBook,
  MessageSquareHeart,
  ThumbsUp,
  TableProperties,
  Rows2,
  TicketPercent,
  Truck,
  ShieldCheck,
  UtensilsCrossed,
  Utensils,
  CalendarRange,
  CalendarClock,
  Phone,
  Forward,
  Cookie,
  ListOrdered,
  Footprints,
  ScrollText,
  Equal,
  Gauge,
  IdCard,
  CalendarCheck,
  Files,
  BookA,
  WholeWord,
  TextQuote,
  LocateFixed,
  Crosshair,
  LayoutDashboard,
  ListVideo,
} from 'lucide-react';

/**
 * The lucide component behind each name a block descriptor may carry.
 *
 * Imported one by one rather than reached for dynamically: lucide ships
 * over six thousand icons, and `icons[name]` would pull every one of
 * them into the editor's bundle to draw the ones we actually use.
 * The list is generated from the registry and kept honest by a test —
 * a block naming an icon that is not here would silently draw the
 * fallback, which looks like a design decision rather than a mistake.
 */
const BLOCK_ICONS: Record<string, LucideIcon> = {
  'align-justify': AlignJustify,
  'arrow-up': ArrowUp,
  'at-sign': AtSign,
  'badge-check': BadgeCheck,
  'building-2': Building2,
  'chart-column': ChartColumn,
  'chevron-down': ChevronDown,
  'chevron-down-square': ChevronDownSquare,
  'chevron-right': ChevronRight,
  'chevrons-up-down': ChevronsUpDown,
  'circle-dot': CircleDot,
  'clipboard-list': ClipboardList,
  code: Code,
  'code-xml': CodeXml,
  'columns-3': Columns3,
  file: File,
  folder: Folder,
  'gallery-horizontal': GalleryHorizontal,
  'gallery-horizontal-end': GalleryHorizontalEnd,
  'grid-3x3': Grid3x3,
  hash: Hash,
  heading: Heading,
  image: Image,
  images: Images,
  languages: Languages,
  'layout-grid': LayoutGrid,
  calendar: CalendarDays,
  'arrow-left-right': ArrowLeftRight,
  layers: Layers,
  'layout-panel-top': LayoutPanelTop,
  link: Link,
  'link-2': Link2,
  mail: Mail,
  'map-pin': MapPin,
  megaphone: Megaphone,
  menu: Menu,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'message-square-quote': MessageSquareQuote,
  'message-square-warning': MessageSquareWarning,
  milestone: Milestone,
  minus: Minus,
  'monitor-play': MonitorPlay,
  'mouse-pointer-click': MousePointerClick,
  'move-vertical': MoveVertical,
  music: Music,
  'panel-top': PanelTop,
  quote: Quote,
  receipt: Receipt,
  'rectangle-vertical': RectangleVertical,
  'rows-3': Rows3,
  search: Search,
  'share-2': Share2,
  'sliders-horizontal': SlidersHorizontal,
  smile: Smile,
  square: Square,
  'square-stack': SquareStack,
  star: Star,
  table: Table,
  tag: Tag,
  tags: Tags,
  anchor: Anchor,
  'book-open-check': BookOpenCheck,
  'list-tree': ListTree,
  'folder-tree': FolderTree,
  'move-horizontal': MoveHorizontal,
  network: Network,
  list: List,
  dot: Dot,
  'layout-panel-left': LayoutPanelLeft,
  'circle-help': CircleHelp,
  infinity: InfinityIcon,
  contact: Contact,
  clock: Clock,
  'file-down': FileDown,
  store: Store,
  'shopping-bag': ShoppingBag,
  'gallery-thumbnails': GalleryThumbnails,
  'badge-percent': BadgePercent,
  'shopping-cart': ShoppingCart,
  'swatch-book': SwatchBook,
  'message-square-heart': MessageSquareHeart,
  'thumbs-up': ThumbsUp,
  'table-properties': TableProperties,
  'rows-2': Rows2,
  'ticket-percent': TicketPercent,
  truck: Truck,
  'shield-check': ShieldCheck,
  'utensils-crossed': UtensilsCrossed,
  utensils: Utensils,
  'calendar-range': CalendarRange,
  'calendar-clock': CalendarClock,
  phone: Phone,
  forward: Forward,
  cookie: Cookie,
  'list-ordered': ListOrdered,
  footprints: Footprints,
  'scroll-text': ScrollText,
  equal: Equal,
  gauge: Gauge,
  'id-card': IdCard,
  'calendar-check': CalendarCheck,
  files: Files,
  'book-a': BookA,
  'whole-word': WholeWord,
  'text-quote': TextQuote,
  'locate-fixed': LocateFixed,
  crosshair: Crosshair,
  'layout-dashboard': LayoutDashboard,
  'list-video': ListVideo,
  timer: Timer,
  type: Type,
  user: User,
  'user-pen': UserPen,
  users: Users,
  video: Video,
};

/**
 * Never null: a block with no icon, or one naming something unknown,
 * gets a neutral square. A missing tile is worse than a plain one — it
 * reads as a broken block rather than an undecorated one.
 */
export function blockIcon(name: string | undefined): LucideIcon {
  return (name && BLOCK_ICONS[name]) || BlockIconFallback;
}

export interface BlockIconProps {
  /** The name from the block's descriptor. */
  name: string | undefined;
  size?: number;
  className?: string;
}

/**
 * A component, rather than callers doing `const Icon = blockIcon(...)`
 * and rendering `<Icon />`: React treats a component built during render
 * as a new type on every pass, remounting it and throwing away whatever
 * state it held. The lint rule that says so is right — the indirection
 * belongs here, once, not at each of the two call sites.
 */
export function BlockIcon({ name, size = 16, className }: BlockIconProps) {
  // `createElement` and not `<Icon />`: assigning a component to a
  // capitalised local and rendering it is how a component gets BUILT
  // during render, and the lint rule cannot tell that apart from this,
  // which only picks one that already exists. This says which it is.
  return createElement(blockIcon(name), {
    size,
    className,
    'aria-hidden': true,
  });
}

/** Exported for the test that holds this list to the registry. */
export const BLOCK_ICON_NAMES = Object.keys(BLOCK_ICONS);
